/**
 * Cucumber World Definition
 *
 * Provides the ICustomWorld interface and world constructor
 * for integrating Playwright with Cucumber BDD tests.
 *
 * @generated by TestRx Automator
 */

import { World, IWorldOptions, setWorldConstructor } from '@cucumber/cucumber';
import {
  BrowserContext,
  Page,
  Browser,
  chromium,
  APIRequestContext,
} from '@playwright/test';

/**
 * Custom World interface for Playwright + Cucumber integration
 *
 * Provides access to browser, context, and page objects
 * within Cucumber step definitions via \`this\`.
 */
export interface ICustomWorld extends World {
  browser: Browser;
  context: BrowserContext;
  page: Page;
  apiContext?: APIRequestContext;
  testName?: string;
  startTime?: number;
  feature?: string;
  debug: boolean;
}

/**
 * Custom World constructor
 *
 * Initializes the world with browser, context, and page.
 * Called before each Cucumber scenario.
 */
export class CustomWorld extends World implements ICustomWorld {
  browser!: Browser;
  context!: BrowserContext;
  page!: Page;
  apiContext?: APIRequestContext;
  testName?: string;
  startTime?: number;
  feature?: string;
  debug = false;

  constructor(options: IWorldOptions) {
    super(options);
  }

  /**
   * Initialize browser, context, and page before each scenario
   */
  async init(): Promise<void> {
    this.browser = await chromium.launch({
      headless: process.env.PLAYWRIGHT_HEADLESS !== 'false',
    });
    this.context = await this.browser.newContext({
      viewport: { width: 1920, height: 1080 },
      ignoreHTTPSErrors: true,
    });
    this.page = await this.context.newPage();
    this.startTime = Date.now();
  }

  /**
   * Cleanup browser resources after each scenario
   */
  async cleanup(): Promise<void> {
    if (this.page) {
      await this.page.close().catch(() => {});
    }
    if (this.context) {
      await this.context.close().catch(() => {});
    }
    if (this.browser) {
      await this.browser.close().catch(() => {});
    }
  }
}

setWorldConstructor(CustomWorld);
